name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      # optionally use a specific version of Go rather than the default one
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1.21.1
        with:
          workdir: golangci-lint/
          github_token: ${{ github.token }}
          reporter: "github-pr-review"
          fail_on_error: true
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: ansible-lint
        uses: reviewdog/action-ansiblelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          workdir: ansible-lint/
          fail_on_error: true
  fix-ansible-lint:
    name: runner / fix-ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: ansible-lint
        uses: Doarakko/action-ansiblelint@fix-fail-on-error
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          workdir: ansible-lint/
          fail_on_error: true
