name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: Doarakko/action-misspell@topic/fai-on-error
        with:
          github_token: ${{ secrets.github_token }}
          reporter: "github-pr-review"
          locale: "US"
          fail_on_error: true
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      # optionally use a specific version of Go rather than the default one
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1.21.1
        with:
          workdir: golangci-lint/
          github_token: ${{ github.token }}
          reporter: "github-pr-review"
          fail_on_error: true
